
language: generic # don't install any environment

script: 
- bash ./deploy.sh
env:
  global:
    - GITHUB_REPO: "juaneml/doc_IV-1920_Proyecto"
    - secure: "$GITHUB_TOKEN"  # <-- from travis-encrypt


